<div class="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
            <div class="card text-black " style="border-radius: 25px;">
                <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                            <p class="text-center h1 fw-bold mb-4 mt-4">Login</p>
                            <form name="user" action="/loginCheck" method="post" class="mx-1 mx-md-4">
                                <?php
                                if(isset($errorLogin)){
                                    ?>
                                    <div class="alert alert-danger" role="alert">
                                        The email or password is incorrect. Please, try again.
                                    </div>
                                    <?php
                                }
                                ?>
                                <div class="form-floating mb-3">
                                    <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" required>
                                    <label for="floatingInput">Email address</label>
                                </div>
                                <div class="form-floating">
                                    <input type="password" name="pass" class="form-control" id="floatingPassword" placeholder="Password" required>
                                    <label for="floatingPassword">Password</label>
                                </div>
                                <div class="mt-3 text-center">
                                    <p>
                                        <button type="submit" class="btn btn-primary btn-lg w-100">Enter</button>
                                    </p>
                                    <p>
                                        <a href="/register">Register</a>
                                    </p>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                 class="img-fluid" alt="Sample image">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
