<div class="container">
    <div class="row">
        <div class="col">
            <h2>Your data:</h2>
            <p>
                <b>Name:</b> <?= $user['name']; ?><br>
                <b>Email:</b> <?= $user['email']; ?>
            </p>
            <h2>Change pass:</h2>
            <p>
                Here will be a form with fields where you can change your password
            </p>
            <h2>Statistics</h2>
            <p>
                Here will be a chart
            </p>
            <h2>Logout:</h2>
            <p>
                <a href="../logout" class="btn btn-primary">Exit</a>
            </p>
        </div>
    </div>
</div>