<div class="container">
    <div class="row">
        <div class="col">
            <h2>Your data:</h2>
            <p>
                <b>Name:</b> <?= $user['name']; ?><br>
                <b>Email:</b> <?= $user['email']; ?>
            </p>
            <a href="/changePassword" class="btn btn-primary mb-2">Change password</a>
            <h2>Statistics for the last 30 days</h2>
            <p>
            <table class="charts-css line" id="my-chart">

                <tbody>
                <?php
                    $htmlCode = '';
                    for($i = 0, $j = 1; $i < 29; $i++, $j++){
                        $htmlCode .= "<tr><td style=\"--start: $averageDaySugar[$i]; --size:  $averageDaySugar[$j]\"> <span class=\"data\"> $statics[$j] </span> </td></tr>";
                    }
                    echo $htmlCode;
                ?>

                </tbody>

            </table>
            </p>
            <h2>Logout:</h2>
            <p>
                <a href="../logout" class="btn btn-primary">Exit</a>
            </p>
        </div>
    </div>
</div>