    <div class="container text-center">
        <div class="row mb-5">
            <div class="col">
                <h2>Your data:</h2>
                <p>
                    <b>Name:</b> <?= $user['name']; ?><br>
                    <b>Email:</b> <?= $user['email']; ?><br>
                </p>
                <a href="/changePassword" class="btn btn-primary mb-2">Change password</a><br>
                <a href="../logout" class="btn btn-primary">Logout</a>
            </div>
        </div>

        <div class="row">
            <div class="col mb-5">
                <h2>Your average sugar in blood for all time:</h2>
                <p class="h1 mb-5"><span class="badge bg-primary"><?= round($averageSugarForAllTime['averageSugarForAllTime'],2) ?></span></p>
                <h2>Statistics for the last 30 days</h2>

                <table class="charts-css line pb-5" id="my-chart">

                    <tbody>
                    <?= $htmlCode; ?>
                    </tbody>

                </table>

            </div>
        </div>
    </div>