<div class="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
            <div class="card text-black " style="border-radius: 25px;">
                <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1" id="tooltipContainer">
                            <p class="text-center h1 fw-bold mb-4 mt-4">Sing up</p>
                            <form action="/register" method="post">

                                <div class="form-floating mb-1 mt-1" data-bs-toggle="tooltip" data-bs-placement="right" title="From 3 to 30 characters. Only letters, numbers and '-' '_' are available">
                                    <input type="text" name="name" class="form-control" id="nameInput" placeholder="name"
                                           value="<?php if(isset($errorValidation['name'])){
                                               echo $_POST['name'];
                                           } ?>" required>
                                    <label for="nameInput">Your name</label>
                                </div>
                                <?php
                                if(isset($errorValidation['name'])){
                                    if(!$errorValidation['name']){
                                    ?>
                                    <div class="alert alert-danger" role="alert">
                                        The name is incorrect. Please, try again.
                                    </div>
                                    <?php
                                }}
                                ?>
                                <div class="form-floating mb-1 mt-1" data-bs-toggle="tooltip" data-bs-placement="right" title="name@example.com">
                                    <input type="email" name="email" class="form-control" id="emailInput" placeholder="name@example.com"
                                           value="<?php if(isset($errorValidation['emailIncorrect'])){
                                               echo $_POST['email'];
                                           } ?>" required>
                                    <label for="emailInput">Your email</label>
                                </div>
                                <?php
                                if(isset($errorValidation['emailIncorrect'])){
                                    if(!$errorValidation['emailIncorrect']){
                                    ?>
                                    <div class="alert alert-danger" role="alert">
                                        The email is incorrect. Please, try again.
                                    </div>
                                    <?php
                                    }elseif(!$errorValidation['emailExist']){
                                        ?>
                                        <div class="alert alert-danger" role="alert">
                                            The email is exists. Please, use a different email.
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                <div class="form-floating mb-1 mt-1" data-bs-toggle="tooltip" data-bs-placement="right" title="From 3 to 30 characters. Only letters, numbers and '-' '_' are available">
                                    <input type="password" name="pass" class="form-control" id="passwordInput" placeholder="Password"
                                           value="<?php if(isset($errorValidation['pass'])){
                                               echo $_POST['pass'];
                                           } ?>" required>
                                    <label for="passwordInput">Password</label>
                                </div>
                                <?php
                                if(isset($errorValidation['pass'])){
                                    if(!$errorValidation['pass']){
                                    ?>
                                    <div class="alert alert-danger" role="alert">
                                        The pass is incorrect. Please, try again.
                                    </div>
                                    <?php
                                }}
                                ?>
                                <div class="form-floating mb-1 mt-1 " data-bs-toggle="tooltip" data-bs-placement="right" title="Repeat please">
                                    <input type="password" name="pass-repeat" class="form-control" id="repeatPasswordInput" placeholder="Password" required>
                                    <label for="repeatPasswordInput">Repeat your password</label>
                                </div>
                                <?php
                                if(isset($errorValidation['passRepeat'])){
                                    if(!$errorValidation['passRepeat']){
                                    ?>
                                    <div class="alert alert-danger" role="alert">
                                        Passwords are not the same. Please, try again.
                                    </div>
                                    <?php
                                }}
                                ?>
                                <div class="mt-3 text-center">
                                    <p>
                                        <button type="submit" class="btn btn-primary btn-lg w-100" >Create my account</button>
                                    </p>
                                    <p>
                                        <a href="/login"">Login</a>
                                    </p>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                 class="img-fluid" alt="Sample image">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

