
<div class="container">
    <div class="row">
        <div class="col">
            <?php
            if(isset($errorPass)){
                if($errorPass == 'incorrect'){
                    ?>
                    <div class="alert alert-danger" role="alert">
                        The password is incorrect. Please, try again.
                    </div>
                    <?php
                }elseif($errorPass == 'notEqual'){ ?>
                    <div class="alert alert-danger" role="alert">
                        The password isn't equal. Please, try again.
                    </div>
                    <?php
                }elseif($errorPass == 'oldPassWrong'){ ?>
                    <div class="alert alert-danger" role="alert">
                        The old password is incorrect. Please, try again.
                    </div>
                    <?php
                }elseif($errorPass == 'noErrors'){ ?>
                    <div class="alert alert-success" role="alert">
                        Your password has been changed
                    </div>
                    <?php
                }
            }
            ?>
            <form name="Sugar" action="/changePassword" method="post">
                <div class="container" id="tooltipContainer">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="InputTime" class="form-label">Your pass:</label>
                                <input type="password" name="old-pass" class="form-control" data-bs-toggle="tooltip" data-bs-placement="top" title="123456789" required>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="InputTime" class="form-label">New pass:</label>
                                <input type="password" name="new-pass" class="form-control" class="form-control" data-bs-toggle="tooltip" data-bs-placement="top" title="From 3 to 30 characters. Only letters, numbers and '-' '_' are available" required>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label for="InputTime" class="form-label">Repeat new pass:</label>
                                <input type="password" name="new-repeat-pass" class="form-control" data-bs-toggle="tooltip" data-bs-placement="top" title="From 3 to 30 characters. Only letters, numbers and '-' '_' are available" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

