<div class="container">
    <div class="row">
        <div class="col h1 text-center">
            <?= $calendar->showMonth(); ?>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped table-bordered text-center">
                <?php  $calendar->showCalendar(); ?>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="col text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-5"><a href="\calendar\<?=  $calendar->lastMonth(); ?>" class="btn btn-primary">Last</a></div>
                        <div class="col-2 h3">Month</div>
                        <div class="col-5"><a href="\calendar\<?=  $calendar->nextMonth(); ?>" class="btn btn-primary">Next</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

