

<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1><?php echo $dayObj->thisDay;?></h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>
                <button id="buttonSigar" type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#formSugar" aria-expanded="false" aria-controls="formSugar">Add sugar</button>
                <button id="buttonMeal" type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#formMealTime" aria-expanded="false" aria-controls="formMealTime">Add meal</button>
            </p>
            <div class="collapse mb-2" id="formSugar">
                <div class="card card-body">
                    <form name="Sugar" action="sugarHandler.php/insert" method="post">
                        <input type="hidden" name="day" value="<?= $dayObj->thisDay; ?>">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputTime" class="form-label">Time</label>
                                        <input type="time" name="sugarTime" class="form-control" id="InputTime" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputNumber" class="form-label">Sugar in blood</label>
                                        <input type="number" placeholder="00.00" step="0.1" min="0" max="200" name="sugar" class="form-control" id="InputNumber" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-center">
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
            <div class="collapse mb-2" id="formMealTime">
                <div class="card card-body">
                    <form name="MealTime" action="sugarHandler.php/insert" method="post">
                        <input type="hidden" name="day" value="<?= $dayObj->thisDay; ?>">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputTime2" class="form-label">Time</label>
                                        <input type="time" name="sugarTime" class="form-control" id="InputTime2" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputInsulin" class="form-label">Insulin</label>
                                        <input type="number" placeholder="00.00" min="0" max="200" name="sugarInsulin" class="form-control" id="InputInsulin" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputBU" class="form-label">Bread units</label>
                                        <input type="number" placeholder="00.00" min="0" max="200" name="sugarBU" class="form-control" id="InputBU" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="InputNumber2" class="form-label">Sugar in blood</label>
                                        <input type="number" placeholder="00.00" step="0.1" min="0" max="200" name="sugar" class="form-control" id="InputNumber2" >
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label for="InputComment" class="form-label">Comment</label>
                                        <textarea class="form-control" placeholder="Enter your comment..." name="sugarComment" id="InputComment" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-center">
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped table-bordered">
                <tr class="text-center">
                    <th>Time</th>
                    <th>Insulin</th>
                    <th>Bread units</th>
                    <th>Sugar</th>
                    <th>Comments</th>
                    <th>Action</th>
                </tr>
                <?php
                if (empty($dayObj->days)){ ?>
                <tr><td colspan='5'>This day has no records yet</td></tr>
                <?php } else{
                foreach ($dayObj->days as $day) {
                $time = substr($day->timeEnter, 0, 5);?>
                <tr><td><?= $time; ?></td>
                    <td><?= $day->insulin; ?></td>
                    <td><?= $day->XE; ?></td>
                    <td><?= $day->sugar_blood; ?></td>
                    <td><?= $day->comments; ?></td>
                    <td class='text-center'>
                        <a href='recordShow.php?id=$day->id_sugar' class='btn btn-primary'><i class="fa fa-pencil"></i></a>
                        <a href='sugarHandler.php/delete?id=$day->id_sugar' class='btn btn-primary'><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                <?php }} ?>
            </table>
        </div>
    </div>
</div>