<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1><?php echo $dayObj->day; ?></h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table class="table table-striped table-bordered">
                <tr class="text-center">
                    <th>Time</th>
                    <th>Insulin</th>
                    <th>Bread units</th>
                    <th>Sugar</th>
                    <th>Comments</th>
                    <th>Action</th>
                </tr>
                <form name='MealTime' action='../update' method='post'>
                    <input type='hidden' name='id_sugar' value='<?= $dayObj->id_sugar; ?>'>
                    <input type='hidden' name='day' value='<?= $dayObj->day; ?>'>
                    <tr><td><input type='time' value='<?= $dayObj->timeEnter; ?>' name='timeEnter' class='form-control' required>
                        </td>
                        <td>
                            <input type='number' value='<?= $dayObj->insulin; ?>' placeholder='00.00' min='0' max='200' name='insulin' class='form-control'>
                        </td>
                        <td>
                            <input type='number' value='<?= $dayObj->bread_units; ?>' placeholder='00.00' min='0' max='200' name='bread_units' class='form-control' id='InputBU'>
                        </td>
                        <td>
                            <input type='number' placeholder='00.00' step='0.1' min='0' max='200' name='sugar_blood' class='form-control' id='InputNumber2' value='<?= $dayObj->sugar_blood; ?>'>
                        </td>
                        <td>
                            <textarea class='form-control' placeholder='Enter your comment...' name='comments' id='InputComment' rows='3'><?= $dayObj->comments; ?></textarea>
                        </td>
                        <td class='text-center'><button type='submit' class='btn btn-primary'>Submit</button>
                        </td>
                    </tr></form>
            </table>
        </div>
    </div>
</div>
